name: hecono_dart
description: A simple bot in dart.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

publish_to: none

dev_dependencies:
  lints: ^2.0.0
  
dependencies: 
  nyxx: ^4.0.0
  nyxx_commands: 
    git: https://github.com/nyxx-discord/nyxx_commands.git
  
